CREATE DATABASE compartir_enlaces;

USE compartir_enlaces;

CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(100) NOT NULL,
name VARCHAR(50) NOT NULL,
avatar VARCHAR(100),
registrationCode VARCHAR(100),
createdAt DATETIME NOT NULL,
modifiedAt DATETIME
);

CREATE TABLE posts (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200)NOT NULL,
link VARCHAR(200)NOT NULL,
description VARCHAR(5000) NOT NULL,
userId INT UNSIGNED NOT NULL,
FOREIGN KEY (userId) REFERENCES users (id),
createdAt DATETIME NOT NULL,
modifiedAt DATETIME
);


/*CREATE TABLE avatar_images (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
image VARCHAR(100) NOT NULL,
userId INT UNSIGNED NOT NULL,
FOREIGN KEY (userId) REFERENCES users (id) 
);*/  



CREATE TABLE likes (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId INT UNSIGNED NOT NULL,
postId INT UNSIGNED NOT NULL,
FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
FOREIGN KEY (postId) REFERENCES posts (id) ON DELETE CASCADE
);

